version: '2.1'

services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes_from:
      - web
    depends_on:
      - web

  web:
    build:
      context: ./web_src
      dockerfile: Dockerfile
    image: 'websrc'
    ports:
      - '127.0.0.1:8000:8000'
    env_file: '.env'
    command: 'gunicorn dj_hero.wsgi:application -w 2 -b :8000'
    volumes:
      - 'cachedata:/cache'
      - 'mediadata:/media'
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: 'postgres'
    image: 'postgres:9.6'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata:
  cachedata:
  mediadata: