# Generated by Django 2.0 on 2018-07-20 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closes_at',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opens_at',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
